version: '3.9'
services:
  identity-server:
    image: modmoto/identity-server:${TAG}
    container_name: identity-server-${CONTAINER_SUFFIX}
    restart: unless-stopped
    expose:
      - 80
    environment:
      - MONGO_DB_CONNECTION_STRING=${MONGO_DB_CONNECTION_STRING}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - FADING_FLAME_SECRET=${FADING_FLAME_SECRET}
  
  mongo-db:
    image: mongo
    container_name: mongo-db-identity-server-${CONTAINER_SUFFIX}
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    command: --wiredTigerCacheSizeGB=1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${DB_SECRET}
    volumes:
      - mongo-db-identity-server:/data/db

networks:
  default:
    external:
      name: caddy

volumes:
  mongo-db-identity-server:
    name: mongo-db-identity-server-${CONTAINER_SUFFIX}
